Fix crash that could occur when writing to WebSocket in CLOSING state.
As flagged in https://github.com/websockets/ws/issues/464, you can
subscribe to the "closed" event for a WebSocket but not a "closing" event.
In both cases, we want to avoid writing to the WebSocket because doing
so will incur a crash:

```
/home/pi/src/rpi-clock/node_modules/rxjs/Subscriber.js:243
            throw err;
            ^

Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/home/pi/src/rpi-clock/node_modules/ws/lib/websocket.js:371:19)
    at SafeSubscriber.observable.subscribe.value [as _next] (/home/pi/src/rpi-clock/src/webserver/src/handler.js:96:27)
    at SafeSubscriber.__tryOrUnsub (/home/pi/src/rpi-clock/node_modules/rxjs/Subscriber.js:239:16)
    at SafeSubscriber.next (/home/pi/src/rpi-clock/node_modules/rxjs/Subscriber.js:186:22)
    at Subscriber._next (/home/pi/src/rpi-clock/node_modules/rxjs/Subscriber.js:126:26)
    at Subscriber.next (/home/pi/src/rpi-clock/node_modules/rxjs/Subscriber.js:90:18)
    at ClientReadableStream.call.on.display (/home/pi/src/rpi-clock/src/webserver/src/handler.js:116:16)
    at emitOne (events.js:115:13)
    at ClientReadableStream.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
```

This commit adds a test for the `readyState` before invoking `send()`.